language: java

arch:
  - amd64
  - ppc64le

jdk:
  - openjdk11
  
cache:
  directories:
    - $HOME/.m2

before_install: 
  - sudo apt update -y
  - sudo apt-get install maven

script:
  - mvn clean
  - mvn install
